import { useEffect, useMemo, useState } from 'react'
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import timeGridPlugin from '@fullcalendar/timegrid'
import interactionPlugin from '@fullcalendar/interaction'
import koLocale from '@fullcalendar/core/locales/ko'
import type { EventClickArg } from '@fullcalendar/core'
import { auth } from './firebase'

type MemberId='me'|'wife'|'son'
type Repeat='none'|'daily'|'weekdays'|'weekly'|'monthly'
type EventItem={id:string;title:string;start:string;end?:string;allDay?:boolean;memberIds:MemberId[];kind?:'event'|'homework'|'homework-complete';homeworkId?:string;completed?:boolean;completedAt?:string;location?:string;memo?:string;repeat?:Repeat}
type Homework={id:string;name:string}
const members=[{id:'me' as MemberId,label:'아빠',icon:'👨',color:'#4285f4'},{id:'wife' as MemberId,label:'엄마',icon:'👩',color:'#9c6ade'},{id:'son' as MemberId,label:'강천',icon:'👦',color:'#34a853'}]
const accountMemberByEmail:Record<string,MemberId>={'dad@family-scheduler.app':'me','mom@family-scheduler.app':'wife','son@family-scheduler.app':'son'}
const homeworkDefaults:Homework[]=[{id:'eli-english',name:'엘리하이(영어)'},{id:'eli-math',name:'엘리하이(수학)'},{id:'eli-science',name:'엘리하이(과학)'},{id:'eli-social',name:'엘리하이(사회)'},{id:'eli-korean',name:'엘리하이(국어)'},{id:'hanja',name:'한자'},{id:'math-calc',name:'수학 연산'},{id:'pretty-writing',name:'예쁜 글씨 쓰기'},{id:'art',name:'미술학원 숙제'}]
const pad=(n:number)=>String(n).padStart(2,'0');const dateKey=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const dateTime=(d:Date)=>`${dateKey(d)}T${pad(d.getHours())}:${pad(d.getMinutes())}`;const uid=()=>crypto.randomUUID?.()??`id-${Date.now()}-${Math.random()}`
const repeatDates=(start:string,repeat:Repeat)=>{if(repeat==='none')return [start];const out=[start];for(let i=1;i<=90&&out.length<24;i++){const d=new Date(`${start.slice(0,10)}T12:00:00`);if(repeat==='daily')d.setDate(d.getDate()+i);else if(repeat==='weekdays'){d.setDate(d.getDate()+i);if(d.getDay()===0||d.getDay()===6)continue}else if(repeat==='weekly')d.setDate(d.getDate()+i*7);else d.setMonth(d.getMonth()+i);out.push(`${dateKey(d)}${start.slice(10)}`)}return out}
const demo:EventItem[]=[{id:'school',title:'학교',start:'2026-09-10T08:50:00',end:'2026-09-10T15:10:00',memberIds:['son']},{id:'math',title:'수학학원',start:'2026-09-10T16:00:00',end:'2026-09-10T17:30:00',memberIds:['son']},{id:'exercise',title:'운동',start:'2026-09-10T18:30:00',end:'2026-09-10T19:30:00',memberIds:['wife']},{id:'gym',title:'헬스',start:'2026-09-10T20:00:00',end:'2026-09-10T21:30:00',memberIds:['me']}]
export default function App(){
 const currentMember=accountMemberByEmail[auth.currentUser?.email??'']
 const [events,setEvents]=useState<EventItem[]>(()=>{try{const x=localStorage.getItem('family-scheduler-events');return x?JSON.parse(x):demo}catch{return demo}});const [selected,setSelected]=useState<MemberId[]>(()=>{try{const x=localStorage.getItem('family-scheduler-members');return x?JSON.parse(x):['me','wife','son']}catch{return ['me','wife','son']}});const [homeworks,setHomeworks]=useState<Homework[]>(()=>{try{const x=localStorage.getItem('family-scheduler-homeworks');return x?JSON.parse(x):homeworkDefaults}catch{return homeworkDefaults}})
 const [homeworkOpen,setHomeworkOpen]=useState(false),[manageOpen,setManageOpen]=useState(false),[homeworkDate,setHomeworkDate]=useState(dateKey(new Date())),[homeworkIds,setHomeworkIds]=useState<string[]>([]),[homeworkName,setHomeworkName]=useState(''),[editing,setEditing]=useState<Homework|null>(null),[modal,setModal]=useState<EventItem|null>(null),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[todayOpen,setTodayOpen]=useState(false)
 useEffect(()=>localStorage.setItem('family-scheduler-events',JSON.stringify(events)),[events]);useEffect(()=>localStorage.setItem('family-scheduler-members',JSON.stringify(selected)),[selected]);useEffect(()=>localStorage.setItem('family-scheduler-homeworks',JSON.stringify(homeworks)),[homeworks])
 const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),1800)};const visible=useMemo(()=>events.filter(e=>e.memberIds.some(m=>selected.includes(m))&&(!search.trim()||`${e.title} ${e.location??''} ${e.memo??''}`.toLowerCase().includes(search.trim().toLowerCase()))),[events,selected,search])
 const calendarEvents=visible.map(e=>{const m=members.find(x=>x.id===e.memberIds[0])??members[0];const done=e.kind==='homework-complete'||(e.kind==='homework'&&e.completed);const school=e.kind==='homework'&&!e.completed&&e.title.includes('학교숙제');const color=done?'#9aa0a6':school?'#f29900':m.color;return {...e,backgroundColor:color,borderColor:color}})
 const addSchedule=(arg:any)=>{const start=new Date(arg.date);setModal({id:uid(),title:'',start:dateTime(start),end:dateTime(new Date(start.getTime()+3600000)),memberIds:currentMember?[currentMember]:[],allDay:false,kind:'event',repeat:'none'})};const clickEvent=(arg:EventClickArg)=>{const e=events.find(x=>x.id===arg.event.id);if(e)setModal(e)}
 const saveEvent=(e:EventItem)=>{if(!e.title.trim())return alert('일정 제목을 입력해주세요.');if(!e.memberIds.length)return alert('최소 한 명을 선택해주세요.');const repeat=e.repeat??'none';const dates=repeatDates(e.start,repeat);const duration=e.end?new Date(e.end).getTime()-new Date(e.start).getTime():3600000;const generated=dates.map((d,i)=>({...e,id:i===0?e.id:uid(),start:d,end:e.end?dateTime(new Date(new Date(d).getTime()+duration)):undefined,repeat:i===0?repeat:'none'}));setEvents(p=>[...p.filter(x=>x.id!==e.id),...generated]);setModal(null);flash(repeat==='none'?'일정을 저장했습니다.':`${generated.length}개의 반복 일정을 만들었습니다.`)}
 const changeEvent=(id:string,start:string,end?:string)=>setEvents(p=>p.map(x=>x.id===id?{...x,start,end}:x));const eventDrop=(arg:any)=>{if(arg.event.start)changeEvent(arg.event.id,dateTime(arg.event.start),arg.event.end?dateTime(arg.event.end):undefined);flash('일정 시간을 변경했습니다.')};const eventResize=(arg:any)=>{if(arg.event.start)changeEvent(arg.event.id,dateTime(arg.event.start),arg.event.end?dateTime(arg.event.end):undefined);flash('일정 시간을 변경했습니다.')}
 const deleteEvent=(e:EventItem)=>{if(!confirm(`'${e.title}' 일정을 삭제할까요?`))return;setEvents(p=>p.filter(x=>x.id!==e.id));setModal(null);flash('일정을 삭제했습니다.')}
 const registerHomework=()=>{if(!homeworkIds.length)return;const chosen=homeworks.filter(h=>homeworkIds.includes(h.id));const fresh=chosen.filter(h=>!events.some(e=>e.kind==='homework'&&e.homeworkId===h.id&&e.start.slice(0,10)===homeworkDate&&!e.completed));const created=fresh.map(h=>({id:uid(),title:`📝 ${h.name}`,start:`${homeworkDate}T00:00:00`,end:`${homeworkDate}T23:59:59`,allDay:true,memberIds:['son'] as MemberId[],kind:'homework' as const,homeworkId:h.id,completed:false}));if(!created.length)return alert('선택한 숙제는 해당 날짜에 모두 이미 등록되어 있습니다.');setEvents(p=>[...p,...created]);setHomeworkOpen(false);setHomeworkIds([]);flash(`${created.length}개 숙제를 등록했습니다.`)}
 const completeHomework=(e:EventItem)=>{if(e.completed)return;const now=new Date();const next={...e,title:`✅ ${e.title.replace(/^📝\s*/,'')}`,completed:true,completedAt:now.toISOString()};const record:EventItem={id:uid(),title:`✅ 숙제 완료 · ${e.title.replace(/^📝\s*/,'')}`,start:dateTime(now),end:dateTime(new Date(now.getTime()+900000)),memberIds:['son'],kind:'homework-complete',homeworkId:e.homeworkId};setEvents(p=>[...p.map(x=>x.id===e.id?next:x),record]);setModal(null);flash('숙제를 완료했습니다.')}
 const addHomework=()=>{const n=homeworkName.trim();if(!n)return;if(homeworks.some(h=>h.name===n))return alert('이미 등록된 숙제입니다.');setHomeworks(p=>[...p,{id:uid(),name:n}]);setHomeworkName('')};const updateHomework=()=>{if(!editing)return;const n=homeworkName.trim();if(!n)return;setHomeworks(p=>p.map(h=>h.id===editing.id?{...h,name:n}:h));setEditing(null);setHomeworkName('')};const deleteHomework=(h:Homework)=>{if(!confirm(`'${h.name}' 숙제 항목을 삭제할까요?`))return;setHomeworks(p=>p.filter(x=>x.id!==h.id));setHomeworkIds(p=>p.filter(x=>x!==h.id))}
 const today=dateKey(new Date());const todayEvents=events.filter(e=>e.start.slice(0,10)===today&&e.kind!=='homework-complete'&&e.memberIds.some(m=>selected.includes(m))).sort((a,b)=>a.start.localeCompare(b.start));const todayHomework=events.filter(e=>e.start.slice(0,10)===today&&e.kind==='homework')
 return <div className="app-shell"><header className="topbar"><div className="brand"><span>📅</span><strong>우리 가족 스케줄러</strong></div><div className="top-actions"><button className="today-summary-btn" onClick={()=>setTodayOpen(p=>!p)}>📌 오늘</button><button className="homework-btn" onClick={()=>{setHomeworkDate(today);setHomeworkIds([]);setManageOpen(false);setHomeworkOpen(true)}}>📝 숙제 체크</button><button className="add-btn" onClick={()=>setModal({id:uid(),title:'',start:dateTime(new Date()),end:dateTime(new Date(Date.now()+3600000)),memberIds:currentMember?[currentMember]:[],kind:'event',repeat:'none'})}>＋ 일정 추가</button></div></header><div className="toolbar"><div className="filters"><strong>가족</strong>{members.map(m=><label className="member-filter" key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={()=>setSelected(p=>p.includes(m.id)?p.filter(x=>x!==m.id):[...p,m.id])}/><span style={{color:m.color}}>{m.icon} {m.label}</span></label>)}</div><div className="search-box">🔍<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="일정 검색"/><button onClick={()=>setSearch('')}>×</button></div></div><main className="calendar-wrap"><FullCalendar plugins={[dayGridPlugin,timeGridPlugin,interactionPlugin]} initialView="timeGridWeek" locale={koLocale} height="calc(100vh - 150px)" headerToolbar={{left:'prev,next today',center:'title',right:'dayGridMonth,timeGridWeek,timeGridDay'}} buttonText={{today:'오늘',month:'월',week:'주',day:'일'}} events={calendarEvents} editable selectable dateClick={addSchedule} eventClick={clickEvent} eventDrop={eventDrop} eventResize={eventResize} nowIndicator allDaySlot weekends={true}/></main>
 {todayOpen&&<div className="today-panel"><div className="today-head"><h2>📌 오늘의 가족 일정</h2><button onClick={()=>setTodayOpen(false)}>×</button></div><div className="today-columns">{members.filter(m=>selected.includes(m.id)).map(m=><section key={m.id}><h3 style={{color:m.color}}>{m.icon} {m.label}</h3>{todayEvents.filter(e=>e.memberIds.includes(m.id)).map(e=><button className="today-item" key={e.id} onClick={()=>{setTodayOpen(false);setModal(e)}}><b>{e.start.slice(11,16)}</b><span>{e.title}</span></button>)}{!todayEvents.some(e=>e.memberIds.includes(m.id))&&<small>오늘 일정 없음</small>}</section>)}</div><div className="today-homework"><b>📝 오늘 숙제</b><span>{todayHomework.length?`${todayHomework.filter(x=>x.completed).length}/${todayHomework.length} 완료`:'등록된 숙제 없음'}</span></div></div>}
 {notice&&<div className="toast">✓ {notice}</div>}
 {homeworkOpen&&<div className="modal-backdrop"><div className="modal homework-modal"><div className="modal-header"><h2>📝 숙제 체크</h2><button onClick={()=>setHomeworkOpen(false)}>×</button></div><h3>숙제 등록 <span className="field-hint">여러 개 선택 가능</span></h3><div className="homework-card-grid">{homeworks.map(h=><button type="button" key={h.id} className={homeworkIds.includes(h.id)?'homework-card selected':'homework-card'} onClick={()=>setHomeworkIds(p=>p.includes(h.id)?p.filter(x=>x!==h.id):[...p,h.id])}><span>{homeworkIds.includes(h.id)?'✓':'□'}</span>{h.name}</button>)}</div><label>날짜<input type="date" value={homeworkDate} onChange={e=>setHomeworkDate(e.target.value)}/></label><div className="homework-modal-actions"><button className="save-btn" disabled={!homeworkIds.length} onClick={registerHomework}>＋ 선택한 숙제 {homeworkIds.length?`${homeworkIds.length}개`:''} 등록</button><button className="manage-btn" onClick={()=>setManageOpen(p=>!p)}>{manageOpen?'▲ 수정 닫기':'⚙ 숙제 수정'}</button></div>{manageOpen&&<div className="homework-manage"><h3>숙제 항목 관리</h3><div className="homework-add-row"><input value={homeworkName} onChange={e=>setHomeworkName(e.target.value)} placeholder={editing?'수정할 숙제 이름':'새 숙제 이름'}/>{editing?<><button onClick={updateHomework}>수정</button><button onClick={()=>{setEditing(null);setHomeworkName('')}}>취소</button></>:<button onClick={addHomework}>＋ 추가</button>}</div>{homeworks.map(h=><div className="homework-row" key={h.id}><span>{h.name}</span><span><button onClick={()=>{setEditing(h);setHomeworkName(h.name)}}>수정</button><button onClick={()=>deleteHomework(h)}>삭제</button></span></div>)}</div>}</div></div>}
 {modal&&<ScheduleModal event={modal} onClose={()=>setModal(null)} onSave={saveEvent} onDelete={deleteEvent} onComplete={completeHomework}/>}</div>
}
function ScheduleModal({event,onClose,onSave,onDelete,onComplete}:{event:EventItem;onClose:()=>void;onSave:(e:EventItem)=>void;onDelete:(e:EventItem)=>void;onComplete:(e:EventItem)=>void}){const [e,setE]=useState(event);if(e.kind==='homework')return <div className="modal-backdrop"><div className="modal homework-complete-modal"><div className="modal-header"><h2>📝 숙제 확인</h2><button onClick={onClose}>×</button></div><div className="homework-detail"><div className={e.completed?'homework-status done':'homework-status'}>{e.completed?'✓ 숙제 완료':'□ 숙제 미완료'}</div><h3>{e.title.replace(/^📝\s*/,'').replace(/^✅\s*/,'')}</h3><p>숙제 날짜: {e.start.slice(0,10)}</p>{e.completed&&e.completedAt&&<p>완료 시간: {new Date(e.completedAt).toLocaleString('ko-KR')}</p>}</div><div className="modal-actions">{!e.completed&&<button className="complete-btn" onClick={()=>onComplete(e)}>✓ 완료</button>}<span/><button onClick={onClose}>닫기</button></div></div></div>
 return <div className="modal-backdrop"><div className="modal"><div className="modal-header"><h2>일정 {event.title?'수정':'추가'}</h2><button onClick={onClose}>×</button></div><label>누구<div className="member-picker">{members.map(m=><button type="button" key={m.id} className={e.memberIds.includes(m.id)?'member-chip selected':'member-chip'} onClick={()=>setE(p=>({...p,memberIds:p.memberIds.includes(m.id)?p.memberIds.filter(x=>x!==m.id):[...p.memberIds,m.id]}))}>{m.icon} {m.label}</button>)}</div></label><label>제목<input autoFocus value={e.title} onChange={x=>setE(p=>({...p,title:x.target.value}))}/></label><div className="form-grid"><label>시작<input type="datetime-local" value={e.start} onChange={x=>setE(p=>({...p,start:x.target.value}))}/></label><label>종료<input type="datetime-local" value={e.end??''} onChange={x=>setE(p=>({...p,end:x.target.value}))}/></label></div><label>반복<select value={e.repeat??'none'} onChange={x=>setE(p=>({...p,repeat:x.target.value as Repeat}))}><option value="none">반복 안 함</option><option value="daily">매일</option><option value="weekdays">평일(월~금)</option><option value="weekly">매주</option><option value="monthly">매월</option></select></label><label>장소<input value={e.location??''} onChange={x=>setE(p=>({...p,location:x.target.value}))}/></label><label>메모<textarea value={e.memo??''} onChange={x=>setE(p=>({...p,memo:x.target.value}))}/></label><div className="modal-actions">{event.title&&<button className="delete-btn" onClick={()=>onDelete(e)}>삭제</button>}<span/><button onClick={onClose}>취소</button><button className="save-btn" onClick={()=>onSave(e)}>저장</button></div></div></div>}
